name: cinema_city
description: Unofficial cinema city repertoire app.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  http: ^0.13.4
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.15
  url_launcher: ^6.2.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  flutter_styled_toast: ^2.1.3
  html: ^0.15.0
  timezone: ^0.9.2
  dio: ^5.3.3
  injectable: ^2.1.0
  get_it: ^7.2.0
  slang: 3.25.0
  slang_flutter: 3.25.0
  cupertino_icons: ^1.0.4
  flutter_local_notifications: ^16.1.0
  flutter_timezone: ^1.0.8
  hive: ^2.1.0
  hive_generator: ^2.0.1
  injectable_generator: ^2.1.3
  hive_flutter: ^1.1.0
  collection: ^1.15.0-nullsafety.4
  rxdart: ^0.27.4
  skeletonizer: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  slang_build_runner: 3.25.0
  bloc_test: ^9.1.5
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
   - assets/filmweb-logo.png

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/icon.png"

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
